name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-action/setup-zig@v3
        with:
          version: 0.13.0

      - name: Build LangReplace
        run: zig build -Doptimize=ReleaseSmall

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Build Installer
        run: & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\LangReplace.iss"

      - name: Upload Portable App
        uses: actions/upload-artifact@v4
        with:
          name: LangReplace
          path: zig-out\bin\LangReplace.exe

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: LangReplace-Setup
          path: installer\Output\LangReplace-Setup.exe
